/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultResultIdRouteImport } from './routes/result.$resultId'
import { Route as ExperienceResultIdRouteImport } from './routes/experience.$resultId'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiResultsResultIdRouteImport } from './routes/api/results.$resultId'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultResultIdRoute = ResultResultIdRouteImport.update({
  id: '/result/$resultId',
  path: '/result/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceResultIdRoute = ExperienceResultIdRouteImport.update({
  id: '/experience/$resultId',
  path: '/experience/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResultsResultIdRoute = ApiResultsResultIdRouteImport.update({
  id: '/api/results/$resultId',
  path: '/api/results/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/processing': typeof ProcessingRoute
  '/start': typeof StartRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/inngest': typeof ApiInngestRoute
  '/experience/$resultId': typeof ExperienceResultIdRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/api/results/$resultId': typeof ApiResultsResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/processing': typeof ProcessingRoute
  '/start': typeof StartRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/inngest': typeof ApiInngestRoute
  '/experience/$resultId': typeof ExperienceResultIdRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/api/results/$resultId': typeof ApiResultsResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/processing': typeof ProcessingRoute
  '/start': typeof StartRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/inngest': typeof ApiInngestRoute
  '/experience/$resultId': typeof ExperienceResultIdRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/api/results/$resultId': typeof ApiResultsResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/processing'
    | '/start'
    | '/api/generate'
    | '/api/inngest'
    | '/experience/$resultId'
    | '/result/$resultId'
    | '/api/results/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/processing'
    | '/start'
    | '/api/generate'
    | '/api/inngest'
    | '/experience/$resultId'
    | '/result/$resultId'
    | '/api/results/$resultId'
  id:
    | '__root__'
    | '/'
    | '/customScript.js'
    | '/processing'
    | '/start'
    | '/api/generate'
    | '/api/inngest'
    | '/experience/$resultId'
    | '/result/$resultId'
    | '/api/results/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  ProcessingRoute: typeof ProcessingRoute
  StartRoute: typeof StartRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ExperienceResultIdRoute: typeof ExperienceResultIdRoute
  ResultResultIdRoute: typeof ResultResultIdRoute
  ApiResultsResultIdRoute: typeof ApiResultsResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$resultId': {
      id: '/result/$resultId'
      path: '/result/$resultId'
      fullPath: '/result/$resultId'
      preLoaderRoute: typeof ResultResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$resultId': {
      id: '/experience/$resultId'
      path: '/experience/$resultId'
      fullPath: '/experience/$resultId'
      preLoaderRoute: typeof ExperienceResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/results/$resultId': {
      id: '/api/results/$resultId'
      path: '/api/results/$resultId'
      fullPath: '/api/results/$resultId'
      preLoaderRoute: typeof ApiResultsResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  ProcessingRoute: ProcessingRoute,
  StartRoute: StartRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiInngestRoute: ApiInngestRoute,
  ExperienceResultIdRoute: ExperienceResultIdRoute,
  ResultResultIdRoute: ResultResultIdRoute,
  ApiResultsResultIdRoute: ApiResultsResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
